### ISSUE TITLE
Exception thrown in 'Document This': Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by buehler** [joelday/vscode-docthis#86] opened 2017-01-31 06:35 UTC
Hey there, I encounter an error when using your plugin, it just happens sometimes (sadly)

I hope the err stack helps you!
Cheers

Platform: darwin

Steps to reproduce the error:
- code a function
- don't save the document
- press the combination for document this

Code excerpt that reproduces the error (optional):

Exception:
{"name":"TypeError","message":"Cannot read property 'text' of undefined","stack":"TypeError: Cannot read property 'text' of undefined\n    at NodeObject.createChildren (/Users/christoph/.vscode/extensions/joelday.docthis-0.3.9/node_modules/typescript/lib/typescript.js:78115:72)\n    at NodeObject.getChildren (/Users/christoph/.vscode/extensions/joelday.docthis-0.3.9/node_modules/typescript/lib/typescript.js:78167:22)\n    at findChildFunc (/Users/christoph/.vscode/extensions/joelday.docthis-0.3.9/out/src/utilities.js:44:11)\n    at Array.forEach (native)\n    at findChildFunc (/Users/christoph/.vscode/extensions/joelday.docthis-0.3.9/out/src/utilities.js:44:25)\n    at Array.forEach (native)\n    at findChildFunc (/Users/christoph/.vscode/extensions/joelday.docthis-0.3.9/out/src/utilities.js:44:25)\n    at Array.forEach (native)\n    at findChildFunc (/Users/christoph/.vscode/extensions/joelday.docthis-0.3.9/out/src/utilities.js:44:25)\n    at Array.forEach (native)"}

**Comment by buehler** [comment] 2017-01-31 06:36
Well.. possible dup of
#85 , #86

**Comment by joelday** [comment] 2017-02-09 17:45
Dupe of #73

**Closed by joelday** 2017-02-09 17:45 UTC
