### ISSUE TITLE
Exception thrown in 'Document This': Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by pKrav75** [joelday/vscode-docthis#80] opened 2017-01-18 10:02 UTC
Platform: win32

Steps to reproduce the error:

Code excerpt that reproduces the error (optional):

Just typed CRTL+ALT D D while cursor was on a function 

Exception:
{"name":"TypeError","message":"Cannot read property 'text' of undefined","stack":"TypeError: Cannot read property 'text' of undefined\n    at NodeObject.createChildren (C:\\Users\\pmr\\.vscode\\extensions\\joelday.docthis-0.3.9\\node_modules\\typescript\\lib\\typescript.js:78115:72)\n    at NodeObject.getChildren (C:\\Users\\pmr\\.vscode\\extensions\\joelday.docthis-0.3.9\\node_modules\\typescript\\lib\\typescript.js:78167:22)\n    at findChildFunc (C:\\Users\\pmr\\.vscode\\extensions\\joelday.docthis-0.3.9\\out\\src\\utilities.js:44:11)\n    at Array.forEach (native)\n    at findChildFunc (C:\\Users\\pmr\\.vscode\\extensions\\joelday.docthis-0.3.9\\out\\src\\utilities.js:44:25)\n    at Array.forEach (native)\n    at findChildFunc (C:\\Users\\pmr\\.vscode\\extensions\\joelday.docthis-0.3.9\\out\\src\\utilities.js:44:25)\n    at Array.forEach (native)\n    at findChildFunc (C:\\Users\\pmr\\.vscode\\extensions\\joelday.docthis-0.3.9\\out\\src\\utilities.js:44:25)\n    at Array.forEach (native)"}

**Comment by shytikov** [comment] 2017-01-20 11:44
Same here, but Windows 64 bit.

**Comment by joelday** [comment] 2017-01-23 16:44
Dupe of #73

**Closed by joelday** 2017-01-23 16:44 UTC
