### ISSUE TITLE
Exception thrown in 'Document Everything': Cannot read property 'getText' of undefined

### ISSUE THREAD

**Issue by garyhwilson** [joelday/vscode-docthis#88] opened 2017-02-03 07:27 UTC
Platform: darwin

Steps to reproduce the error:

Code excerpt that reproduces the error (optional):

Exception:
{"name":"TypeError","message":"Cannot read property 'getText' of undefined","stack":"TypeError: Cannot read property 'getText' of undefined\n    at Documenter._emitClassDeclaration (/Users/garyhwilson/.vscode/extensions/joelday.docthis-0.3.10/out/src/documenter.js:240:42)\n    at Documenter._documentNode (/Users/garyhwilson/.vscode/extensions/joelday.docthis-0.3.10/out/src/documenter.js:186:22)\n    at documentable.forEach.node (/Users/garyhwilson/.vscode/extensions/joelday.docthis-0.3.10/out/src/documenter.js:83:38)\n    at Array.forEach (native)\n    at Documenter.documentEverything (/Users/garyhwilson/.vscode/extensions/joelday.docthis-0.3.10/out/src/documenter.js:81:22)\n    at runCommand (/Users/garyhwilson/.vscode/extensions/joelday.docthis-0.3.10/out/src/extension.js:116:24)\n    at runCommand (/Users/garyhwilson/.vscode/extensions/joelday.docthis-0.3.10/out/src/extension.js:66:9)\n    at context.subscriptions.push.vs.commands.registerTextEditorCommand (/Users/garyhwilson/.vscode/extensions/joelday.docthis-0.3.10/out/src/extension.js:115:9)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:22263\n    at e.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:13:14855)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:22229\n    at t.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:19624)\n    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:2729)\n    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:8:15667)\n    at d (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:8:16344)\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)"}

**Comment by joelday** [comment] 2017-02-09 17:46
Dupe of #73

**Closed by joelday** 2017-02-09 17:46 UTC
