### ISSUE TITLE
Exception thrown in 'Document This': Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by riteshrao** [joelday/vscode-docthis#84] opened 2017-01-30 06:10 UTC
Platform: darwin

Steps to reproduce the error:
Keyboard short cut on an interface definition. Seems to happen more often post a cut and paste operation. Executing the action again after a few seconds works however.

Code excerpt that reproduces the error (optional):

Exception:
{"name":"TypeError","message":"Cannot read property 'text' of undefined","stack":"TypeError: Cannot read property 'text' of undefined\n    at NodeObject.createChildren (/Users/rrao/.vscode/extensions/joelday.docthis-0.3.10/node_modules/typescript/lib/typescript.js:78115:72)\n    at NodeObject.getChildren (/Users/rrao/.vscode/extensions/joelday.docthis-0.3.10/node_modules/typescript/lib/typescript.js:78167:22)\n    at findChildFunc (/Users/rrao/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:44:11)\n    at Array.forEach (native)\n    at findChildFunc (/Users/rrao/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:44:25)\n    at Array.forEach (native)\n    at findChildFunc (/Users/rrao/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:44:25)\n    at Array.forEach (native)\n    at findChildFunc (/Users/rrao/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:44:25)\n    at Array.forEach (native)"}

**Comment by joelday** [comment] 2017-02-09 17:46
Dupe of #73

**Closed by joelday** 2017-02-09 17:46 UTC
