### ISSUE TITLE
Exception thrown in 'Document This': Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by erdii** [joelday/vscode-docthis#85] opened 2017-01-30 09:21 UTC
Platform: linux

Steps to reproduce the error:

Code excerpt that reproduces the error (optional):

Exception:
{"name":"TypeError","message":"Cannot read property 'text' of undefined","stack":"TypeError: Cannot read property 'text' of undefined\n    at NodeObject.createChildren (/home/erdii/.vscode/extensions/joelday.docthis-0.3.10/node_modules/typescript/lib/typescript.js:78115:72)\n    at NodeObject.getChildren (/home/erdii/.vscode/extensions/joelday.docthis-0.3.10/node_modules/typescript/lib/typescript.js:78167:22)\n    at findChildFunc (/home/erdii/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:44:11)\n    at Array.forEach (native)\n    at findChildFunc (/home/erdii/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:44:25)\n    at Array.forEach (native)\n    at findChildFunc (/home/erdii/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:44:25)\n    at Array.forEach (native)\n    at findChildFunc (/home/erdii/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:44:25)\n    at Array.forEach (native)\n    at findChildFunc (/home/erdii/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:44:25)\n    at Array.forEach (native)\n    at findChildFunc (/home/erdii/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:44:25)\n    at Object.findChildForPosition (/home/erdii/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:46:5)\n    at Documenter.documentThis (/home/erdii/.vscode/extensions/joelday.docthis-0.3.10/out/src/documenter.js:51:28)\n    at runCommand (/home/erdii/.vscode/extensions/joelday.docthis-0.3.10/out/src/extension.js:110:24)"}

**Comment by joelday** [comment] 2017-02-09 17:45
Dupe of #73

**Closed by joelday** 2017-02-09 17:45 UTC
