### ISSUE TITLE
Exception thrown in 'Document This': Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by Roustalski** [joelday/vscode-docthis#110] opened 2017-02-17 15:22 UTC
* Check to see if this might have been reported already. *
Platform: darwin

Steps to reproduce the error:

Place cursor above public function definition inside a typescript file. ctl+alt+d two times. Boom.

Code excerpt that reproduces the error (optional):

Exception:
{"name":"TypeError","message":"Cannot read property 'text' of undefined","stack":"TypeError: Cannot read property 'text' of undefined\n    at NodeObject.createChildren (/Users/russellwatson/.vscode/extensions/joelday.docthis-0.3.11/node_modules/typescript/lib/typescript.js:79749:72)\n    at NodeObject.getChildren (/Users/russellwatson/.vscode/extensions/joelday.docthis-0.3.11/node_modules/typescript/lib/typescript.js:79801:22)\n    at findChildFunc (/Users/russellwatson/.vscode/extensions/joelday.docthis-0.3.11/out/src/utilities.js:55:11)\n    at Array.forEach (native)\n    at findChildFunc (/Users/russellwatson/.vscode/extensions/joelday.docthis-0.3.11/out/src/utilities.js:55:25)\n    at Array.forEach (native)\n    at findChildFunc (/Users/russellwatson/.vscode/extensions/joelday.docthis-0.3.11/out/src/utilities.js:55:25)\n    at Array.forEach (native)\n    at findChildFunc (/Users/russellwatson/.vscode/extensions/joelday.docthis-0.3.11/out/src/utilities.js:55:25)\n    at Array.forEach (native)"}

**Comment by joelday** [comment] 2017-02-17 17:32
Dupe of #73

**Closed by joelday** 2017-02-17 17:32 UTC
