### ISSUE TITLE
Exception thrown in 'Document Everything Visible': Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by dayanand-saraswati** [joelday/vscode-docthis#101] opened 2017-02-10 05:14 UTC
Platform: darwin

Steps to reproduce the error:

Code excerpt that reproduces the error (optional):

Exception:
{"name":"TypeError","message":"Cannot read property 'text' of undefined","stack":"TypeError: Cannot read property 'text' of undefined\n    at NodeObject.createChildren (/Users/dsaraswati/.vscode/extensions/joelday.docthis-0.3.10/node_modules/typescript/lib/typescript.js:78115:72)\n    at NodeObject.getChildren (/Users/dsaraswati/.vscode/extensions/joelday.docthis-0.3.10/node_modules/typescript/lib/typescript.js:78167:22)\n    at findChildrenOfKind (/Users/dsaraswati/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:66:10)\n    at node.getChildren.forEach.c (/Users/dsaraswati/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:70:36)\n    at Array.forEach (native)\n    at findChildrenOfKind (/Users/dsaraswati/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:66:24)\n    at node.getChildren.forEach.c (/Users/dsaraswati/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:70:36)\n    at Array.forEach (native)\n    at findChildrenOfKind (/Users/dsaraswati/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:66:24)\n    at node.getChildren.forEach.c (/Users/dsaraswati/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:70:36)\n    at Array.forEach (native)\n    at findChildrenOfKind (/Users/dsaraswati/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:66:24)\n    at node.getChildren.forEach.c (/Users/dsaraswati/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:70:36)\n    at Array.forEach (native)\n    at findChildrenOfKind (/Users/dsaraswati/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:66:24)\n    at node.getChildren.forEach.c (/Users/dsaraswati/.vscode/extensions/joelday.docthis-0.3.10/out/src/utilities.js:70:36)"}

**Comment by joelday** [comment] 2017-02-20 06:38
Dupe of #73

**Closed by joelday** 2017-02-20 06:38 UTC
