### ISSUE TITLE
Exception thrown in 'Document This': Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by tiefling** [joelday/vscode-docthis#102] opened 2017-02-10 08:48 UTC
Platform: win32

Steps to reproduce the error:

Code excerpt that reproduces the error (optional):

Exception:
{"name":"TypeError","message":"Cannot read property 'text' of undefined","stack":"TypeError: Cannot read property 'text' of undefined\n    at Documenter._emitMemberOf (C:\\Users\\tempo_000\\.vscode\\extensions\\joelday.docthis-0.3.10\\out\\src\\documenter.js:302:56)\n    at Documenter._emitMethodDeclaration (C:\\Users\\tempo_000\\.vscode\\extensions\\joelday.docthis-0.3.10\\out\\src\\documenter.js:294:14)\n    at Documenter._documentNode (C:\\Users\\tempo_000\\.vscode\\extensions\\joelday.docthis-0.3.10\\out\\src\\documenter.js:206:22)\n    at Documenter.documentThis (C:\\Users\\tempo_000\\.vscode\\extensions\\joelday.docthis-0.3.10\\out\\src\\documenter.js:58:34)\n    at runCommand (C:\\Users\\tempo_000\\.vscode\\extensions\\joelday.docthis-0.3.10\\out\\src\\extension.js:110:24)\n    at runCommand (C:\\Users\\tempo_000\\.vscode\\extensions\\joelday.docthis-0.3.10\\out\\src\\extension.js:66:9)\n    at context.subscriptions.push.vs.commands.registerTextEditorCommand (C:\\Users\\tempo_000\\.vscode\\extensions\\joelday.docthis-0.3.10\\out\\src\\extension.js:109:9)\n    at c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\out\\vs\\workbench\\node\\extensionHostProcess.js:14:22263\n    at e.edit (c:\\Program Files (x86)\\Micros

**Comment by joelday** [comment] 2017-02-10 17:18
Dupe of #73

**Closed by joelday** 2017-02-10 17:18 UTC
