### ISSUE TITLE
Exception thrown in 'Document This': Could not find file: '/Users/CC/code/faConsultancyFe/src/quality-check/index.es6'.

### ISSUE THREAD

**Issue by ZhangCheng-zh** [joelday/vscode-docthis#72] opened 2017-01-11 03:43 UTC
Platform: darwin

Steps to reproduce the error:

Code excerpt that reproduces the error (optional):

Exception:
{"name":"Error","message":"Could not find file: '/Users/CC/code/faConsultancyFe/src/quality-check/index.es6'.","stack":"Error: Could not find file: '/Users/CC/code/faConsultancyFe/src/quality-check/index.es6'.\n    at getValidSourceFile (/Users/CC/.vscode/extensions/joelday.docthis-0.3.7/node_modules/typescript/lib/typescript.js:78776:23)\n    at Object.getSyntacticDiagnostics (/Users/CC/.vscode/extensions/joelday.docthis-0.3.7/node_modules/typescript/lib/typescript.js:78983:52)\n    at Documenter._getSourceFile (/Users/CC/.vscode/extensions/joelday.docthis-0.3.7/out/src/documenter.js:176:24)\n    at Documenter.documentThis (/Users/CC/.vscode/extensions/joelday.docthis-0.3.7/out/src/documenter.js:46:33)\n    at runCommand (/Users/CC/.vscode/extensions/joelday.docthis-0.3.7/out/src/extension.js:110:24)\n    at runCommand (/Users/CC/.vscode/extensions/joelday.docthis-0.3.7/out/src/extension.js:66:9)\n    at context.subscriptions.push.vs.commands.registerTextEditorCommand (/Users/CC/.vscode/extensions/joelday.docthis-0.3.7/out/src/extension.js:109:9)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:16738\n    at e.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:11:14547)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:16704"}

**Comment by joelday** [comment] 2017-01-11 03:55
Dupe of #71. Fixing now. Thank you!

**Closed by joelday** 2017-01-11 03:55 UTC
