### ISSUE TITLE
Exception thrown in 'Document This': Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by aagavin** [joelday/vscode-docthis#74] opened 2017-01-12 23:57 UTC
Platform: linux

Steps to reproduce the error:

Code excerpt that reproduces the error (optional):

Exception:
{"name":"TypeError","message":"Cannot read property 'text' of undefined","stack":"TypeError: Cannot read property 'text' of undefined\n    at NodeObject.createChildren (/home/aaron/.vscode/extensions/joelday.docthis-0.3.9/node_modules/typescript/lib/typescript.js:78115:72)\n    at NodeObject.getChildren (/home/aaron/.vscode/extensions/joelday.docthis-0.3.9/node_modules/typescript/lib/typescript.js:78167:22)\n    at findChildFunc (/home/aaron/.vscode/extensions/joelday.docthis-0.3.9/out/src/utilities.js:44:11)\n    at Array.forEach (native)\n    at findChildFunc (/home/aaron/.vscode/extensions/joelday.docthis-0.3.9/out/src/utilities.js:44:25)\n    at Array.forEach (native)\n    at findChildFunc (/home/aaron/.vscode/extensions/joelday.docthis-0.3.9/out/src/utilities.js:44:25)\n    at Array.forEach (native)\n    at findChildFunc (/home/aaron/.vscode/extensions/joelday.docthis-0.3.9/out/src/utilities.js:44:25)\n    at Array.forEach (native)"}

**Comment by joelday** [comment] 2017-01-13 06:07
Dupe of #73

**Closed by joelday** 2017-01-13 06:07 UTC
